export const FETCH_PRODUCTS_SUCCES = 'FETCH_PRODUCTS_SUCCES';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const FETCH_PRODUCTS_IN_CART_SUCCES = 'FETCH_PRODUCTS_IN_CART_SUCCES';
export const FETCH_USER_INFOS_SUCCES = 'FETCH_USER_INFOS_SUCCES';
export const REMOVE_USER_INFOS_SUCCES = 'REMOVE_USER_INFOS_SUCCES';


